source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios,'10.0'
use_frameworks!

target 'MyDemo' do
  pod 'CTMediator'
  
  pod 'GoodsList', :path => 'MyModule/GoodsList'
  pod 'GoodsListCategory', :path => 'MyModule/GoodsListCategory'
  
  pod 'GoodsDetail', :path => 'MyModule/GoodsDetail'
  pod 'GoodsDetailExtension', :path => 'MyModule/GoodsDetailExtension'
end
